target-version = "py312"
line-length = 120
indent-width = 4
cache-dir= "/dev/null"

# fix-only = true
fix = true
extend-exclude = [
  ".aws",
  ".circleci",
  ".ebextensions",
  ".github",
  "bootstrap",
  "config",
  "database",
  "docs",
  "laradock",
  "logs",
  "ops",
  "public",
  "resources",
  "routs",
  "shellscripts",
  "storage",
  "vendor",
  "*.php",
  "*.js",
  "*.xml",
  "*.json",
  "*.lock",
  "*.yml",
  "*.yaml",
  "*.md",
]

ignore = [
  "D100", # missing docstring in public module
  "D104", # missing docstring in public package
  "D213", # multi-line docstring summary should start at the second line
  "D203", # 1 blank line required before class docstring
  "E501", # line too long
]


[lint]
ignore = ["E203"]
ignore-init-module-imports = false

[lint.flake8-annotations]
mypy-init-return = true
suppress-dummy-args = false
allow-star-arg-any = false

[lint.mccabe]
max-complexity = 15

[lint.per-file-ignores]
"__init__.py" = ["F401", "D104"]
"test_*.py" = ["S101", "D", "T20"]
"**/tests/**" = ["S101", "D", "T20"]
"scripts/**" = ["T20"]

[lint.pydocstyle]
convention = "google"

[lint.isort]
known-first-party = ["your_project"]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[format]
docstring-code-format = true
docstring-code-line-length = 120
indent-style = "space"
line-ending = "lf"
quote-style = "double"
