[project]
name = "app"
version = "0.1.0"
description = "python sandbox"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marker-pdf>=1.8.2",
    "paddleocr>=3.1.0",
    "paddlepaddle>=3.1.0",
    "psutil>=7.0.0",
    "pdf-yaml-bookmark>=0.0.4",
    "ruff>=0.12.7",
]
